// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, deprecated_colon_for_default_value
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeUZXYaRO48B45iyIIXVS08WeW4Bi01qM',
    appId: '1:740472649628:web:5ada402b25d76e792d3a59',
    messagingSenderId: '740472649628',
    projectId: 'brew-crew-6c3f9',
    authDomain: 'brew-crew-6c3f9.firebaseapp.com',
    storageBucket: 'brew-crew-6c3f9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSjDEB7s0jd1ZUee_gM3Wstl3wr27r7ZE',
    appId: '1:740472649628:android:52e20863938afbd02d3a59',
    messagingSenderId: '740472649628',
    projectId: 'brew-crew-6c3f9',
    storageBucket: 'brew-crew-6c3f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATSQBzPqn6l8csH3awk5uxsLUxvC2yC78',
    appId: '1:740472649628:ios:e67a1823d88bdd742d3a59',
    messagingSenderId: '740472649628',
    projectId: 'brew-crew-6c3f9',
    storageBucket: 'brew-crew-6c3f9.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATSQBzPqn6l8csH3awk5uxsLUxvC2yC78',
    appId: '1:740472649628:ios:e67a1823d88bdd742d3a59',
    messagingSenderId: '740472649628',
    projectId: 'brew-crew-6c3f9',
    storageBucket: 'brew-crew-6c3f9.appspot.com',
    iosBundleId: 'com.example.brewCrew',
  );
}
